language: python
install:
  - pip install -r vvp-magics/requirements.txt
before_script: cd vvp-magics
script:
  - python -m unittest
  - python setup.py sdist

jobs:
  include:
  - language: ruby
    services: docker
    script:
      - docker build -t vvp-jupyter .