name: "Continuous Integration"

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    env:
      # For now, skip the integration tests, until we have a locally running
      # Ververica Platform to integrate against.
      SKIP_INTEGRATION_TESTS: 1
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest

      - name: Build Source Distribution
        run: python setup.py sdist

      - name: Build Docker Image
        run: docker build --iidfile .imageid .
